name: flutter_polyline_point
description: A flutter plugin that decodes encoded google polyline string into list of geo-coordinates suitable for showing route/polyline on maps
version: 0.0.1
homepage: https://github.com/TesfalemNigussie/flutter_polyline_point
environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
